http:
  routers:
    sveltekit-main: # Svelte Kit for Handling Frontend
      service: sveltekit
      rule: PathPrefix(`/`)
    fiber-main: # Fiber to handle backend part
      service: fiber
      rule: PathPrefix(`/api`)
  services:
    sveltekit:
      loadBalancer:
        servers:
          - url: http://localhost:3427
    fiber:
      loadBalancer:
        servers:
          - url: http://localhost:3428
