http:
  routers:
    sveltekit-main: # Svelte Kit for Handling Frontend
      service: sveltekit
      rule: PathPrefix(`/`)
    fastapi-main: # FastAPI to handle backend part
      service: fast-api
      rule: PathPrefix(`/api`)
  services:
    sveltekit:
      loadBalancer:
        servers:
          - url: http://localhost:3427
    fast-api:
      loadBalancer:
        servers:
          - url: http://localhost:3428
